### ISSUE TITLE
How to apply 'robot_namespace' in blueprint

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/UE_msgs#18]
Hi @yuokamoto,

I am currently spawn actor(inherited from RRBaseRobot) in runtime using ['SpawnEntity'](https://github.com/rapyuta-robotics/UE_msgs/blob/devel/srv/SpawnEntity.srv) service.  
SpawnEntity service has 'robot_namespace' attribute, so I would like to apply namespace to actor in blueprint.  
Could you please let me know how I can do it?

**Comment by yuokamoto** [comment]
https://github.com/user-attachments/assets/af8887d2-461f-4606-bc6a-d7e3c9036f0f

you can set RobotUniqueName. if you want to use actor name as namespace, you can check the Use Actor Name as namespace.

**Comment by yuokamoto** [comment]
https://github.com/user-attachments/assets/efaf7d50-ea11-48d6-a378-75188bfd984b

you can use RobotUniqueName. if you want to use actor name as namespace, you can check Use Actor Name as Namespace.

**Comment by james-yoo** [comment]
@yuokamoto,

Thanks for your quick response. Your video shows that a robot(actor) is placed in level before simulation start. In my case, actor is spawned dynamically in runtime using ros2 service interface and blueprint as below.
  
![Image](https://github.com/user-attachments/assets/4745176d-7291-489e-b97a-441fa442546e)  
  
I would like to apply namespace to distinguish each topics of dynamically spawned actor(=robot).

**Comment by yuokamoto** [comment]
Sorry, I may not get your question but just use field robot_namespace in service request does not meet your requirement?
https://github.com/yuokamoto/rclUE_client_example/blob/9dff4034f160c9d67abf04e57fa05b1b978aea0e/rclUE_client_example/rclUE_client_example/common.py#L178

**Comment by james-yoo** [comment]
@yuokamoto,

Let me ask you "How can I spawn actor using ros2 CLI?"
For example,
ros2 service call /ue2ros/spawn_actor ue_srvs/srv/SpawnEntity "{xml: ' ', robot_namespace: 'test1', ... }"

**Comment by yuokamoto** [comment]
```
ros2 service call /SpawnEntity ue_msgs/srv/SpawnEntity "xml: 'BP_ROSSimpleCharacter'
robot_namespace: 'test'
state:
  name: 'character1'
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
tags: []
json_parameters: ''" 
```
